//
//  HWStompCommand.m
//  huwai
//
//  Created by crazylhf on 15/4/17.
//  Copyright (c) 2015年 zq. All rights reserved.
//

#import "HWStompCommand.h"

HWDEFINE_GLOBALSTRING(HWStompCmd_ABORT,         @"ABORT");
HWDEFINE_GLOBALSTRING(HWStompCmd_BEGIN,         @"BEGIN");
HWDEFINE_GLOBALSTRING(HWStompCmd_ERROR,         @"ERROR");

HWDEFINE_GLOBALSTRING(HWStompCmd_SEND,          @"SEND");
HWDEFINE_GLOBALSTRING(HWStompCmd_COMMIT,        @"COMMIT");

HWDEFINE_GLOBALSTRING(HWStompCmd_MESSAGE,       @"MESSAGE");
HWDEFINE_GLOBALSTRING(HWStompCmd_RECEIPT,       @"RECEIPT");

HWDEFINE_GLOBALSTRING(HWStompCmd_CONNECT,       @"CONNECT");
HWDEFINE_GLOBALSTRING(HWStompCmd_CONNECTED,     @"CONNECTED");
HWDEFINE_GLOBALSTRING(HWStompCmd_DISCONNECT,    @"DISCONNECT");

HWDEFINE_GLOBALSTRING(HWStompCmd_SUBSCRIBE,     @"SUBSCRIBE");
HWDEFINE_GLOBALSTRING(HWStompCmd_UNSUBSCRIBE,   @"UNSUBSCRIBE");
