//
//  MIStompCommand.m
//  huwai
//
//  Created by crazylhf on 15/4/17.
//  Copyright (c) 2015年 zq. All rights reserved.
//

#import "MIStompCommand.h"

MIDEFINE_GLOBALSTRING(MIStompCmd_ABORT,         @"ABORT");
MIDEFINE_GLOBALSTRING(MIStompCmd_BEGIN,         @"BEGIN");
MIDEFINE_GLOBALSTRING(MIStompCmd_ERROR,         @"ERROR");

MIDEFINE_GLOBALSTRING(MIStompCmd_SEND,          @"SEND");
MIDEFINE_GLOBALSTRING(MIStompCmd_COMMIT,        @"COMMIT");

MIDEFINE_GLOBALSTRING(MIStompCmd_MESSAGE,       @"MESSAGE");
MIDEFINE_GLOBALSTRING(MIStompCmd_RECEIPT,       @"RECEIPT");

MIDEFINE_GLOBALSTRING(MIStompCmd_CONNECT,       @"CONNECT");
MIDEFINE_GLOBALSTRING(MIStompCmd_CONNECTED,     @"CONNECTED");
MIDEFINE_GLOBALSTRING(MIStompCmd_DISCONNECT,    @"DISCONNECT");

MIDEFINE_GLOBALSTRING(MIStompCmd_SUBSCRIBE,     @"SUBSCRIBE");
MIDEFINE_GLOBALSTRING(MIStompCmd_UNSUBSCRIBE,   @"UNSUBSCRIBE");
